server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/peopledb
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: PEOPLE-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
      
      